# Generated by Django 3.1.2 on 2020-11-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0005_basket_order_productinbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='equipment',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
