# Generated by Django 3.1.2 on 2020-11-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0007_auto_20201111_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(default=1, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.TextField(default=1, verbose_name='Имя покупателя'),
            preserve_default=False,
        ),
    ]
