# Generated by Django 3.1.2 on 2020-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0008_auto_20201115_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=64, verbose_name='Имя покупателя'),
        ),
    ]
