# Generated by Django 3.1.2 on 2020-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0009_auto_20201115_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
    ]
