# Generated by Django 3.1.2 on 2020-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0010_auto_20201116_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.CharField(default=1, max_length=256, verbose_name='Товары в заказе'),
            preserve_default=False,
        ),
    ]
