# Generated by Django 3.1.2 on 2020-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0011_order_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('0', 'Курьером'), ('1', 'Почтой'), ('2', 'Самовывоз')], default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('0', 'Наличными'), ('1', 'Наложенным платежом'), ('2', 'Картой онлайн')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
