# Generated by Django 3.1.2 on 2020-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0012_auto_20201122_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='http://127.0.0.1:8000/product_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('0', 'Курьером'), ('1', 'Почтой'), ('2', 'Самовывоз')], default='0', max_length=32, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('0', 'Наличными'), ('1', 'Наложенным платежом'), ('2', 'Картой онлайн')], default='0', max_length=32, verbose_name='Оплата'),
        ),
    ]
