# Generated by Django 3.1.2 on 2020-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_market', '0013_auto_20201128_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
    ]
